### PR TITLE
Template and styles of the main component  in separate files.

### PR DESCRIPTION
**Pull request by bampakoa**
Move component template and styles in separate files.

### CODE REVIEW

**Comment by stevermeister** [comment]
actually it was a problem with package compilation that's why we had to do it in such way

**Comment by bampakoa** [comment]
Does the problem persist?

**Comment by stevermeister** [comment]
well, unfortunately we still did not solve it.
so I would really appreciate if you could help.

**Comment by bampakoa** [comment]
I would be glad! Could you share some details?

**Comment by stevermeister** [comment]
I guess @NepipenkoIgor @yarikmlb could tell you more about compilation problems.

As far as I remember it was about broken path to the template and styles in the build.

**Comment by bampakoa** [comment]
@NepipenkoIgor @yarikmlb I am at your disposal about the compilation problem that @stevermeister mentioned.

**Comment by NepipenkoIgor** [comment]
@bampakoa  When we use separate template and style's file after  installing   package it can't resolve path to them. That why we should after compilation insert inline template and styles (  manually or using gulp).

You can play with compilation. Use `npm build` . In dist forlder you will see all files, metadata and so on

**Comment by bampakoa** [comment]
@NepipenkoIgor OK, I can see the problem now. Just curious...why don't you use `ng build` directly from the CLI? I can see that you have commented out **aot** specific properties in `tsconfig-aot.json`. Why is that?

**Comment by NepipenkoIgor** [comment]
@bampakoa I think we played with aot before aot have been added to cli. You can simplify all things and use cli. But i am not sure does it generate metadata.json

**Comment by bampakoa** [comment]
@NepipenkoIgor you are right. Thanks for clarifying!

**Pull request closed without merging**
